//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTests
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int ID_Contract { get; set; }
        public System.DateTime Date_Conclusion { get; set; }
        public System.DateTime Valid_For { get; set; }
        public int ID_Object { get; set; }
        public int ID_Employee { get; set; }
        public int ID_Equipment { get; set; }
        public decimal Price { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Main_Equipment_Boiler_ Main_Equipment_Boiler_ { get; set; }
        public virtual Object Object { get; set; }
    }
}
