//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Учет_сделок.Models_BD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AccountingforTransactionsEntities : DbContext
    {
        public AccountingforTransactionsEntities()
            : base("name=AccountingforTransactionsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bank_Details> Bank_Details { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<Contract> Contract { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Fuel> Fuel { get; set; }
        public virtual DbSet<Main_Equipment_Boiler_> Main_Equipment_Boiler_ { get; set; }
        public virtual DbSet<Object> Object { get; set; }
        public virtual DbSet<Type_Fuel> Type_Fuel { get; set; }
    }
}
